// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import { renderMarkdown } from './converter/markdownToHtml';
import { convertHtmlToPdf } from './converter/htmlToPdf';

// This method is called when the extension is activated
// Your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	// This line of code will only be executed once when your extension is activated
	console.log('Extension: "markdown-pdf-enhanced" is now active!');

	// The command has been defined in the package.json file
	// Below is the implementation
	const disposable = vscode.commands.registerCommand('markdown-pdf-enhanced.convert', async () => {
		const editor = vscode.window.activeTextEditor;

		// Simple check that a markdown file is open in the active editor.
		if (!editor || editor.document.languageId !== 'markdown') {
			vscode.window.showErrorMessage('Please open a Markdown file to convert.');
			return;
		}

		// Get the markdown content to convert
		const markdownContent = editor.document.getText();

		vscode.window.showInformationMessage("Conversion to PDF started...");
		const mdFilePath = editor.document.uri.fsPath;
		const outputDir = path.dirname(mdFilePath);
		const baseName = path.basename(mdFilePath, path.extname(mdFilePath));

		const html = renderMarkdown(markdownContent);
		const tempHtmlPath = path.join( outputDir, "shrfgffusezdfgusrwefsd.html");

		await fs.writeFile(tempHtmlPath, html);

		const outputPath = path.join( outputDir, `${baseName}.pdf`);

		await convertHtmlToPdf(tempHtmlPath, outputPath, {
			headerTemplate: `<div style="font-size:10px; width:100%; text-align:left; padding-left:1cm;">Generated by Markdown PDF Enhanced</div>`,
			footerTemplate: `
				<div style="font-size:10px; width:100%; text-align:right; padding-right:1cm;">
					Page <span class="pageNumber"></span> of <span class="totalPages"></span>
				</div>
			`,
			displayHeaderFooter: true,
			margin: {
				top: '1.5cm',
				bottom: '1.5cm',
				left: '1cm',
				right: '1cm'
			}
		});



	    vscode.window.showInformationMessage(`PDF generated: ${outputPath}`);

	});

	context.subscriptions.push(disposable);
}

// This method is called when your extension is deactivated
export function deactivate() {}
